ufo-kit/ufo-filters

- src/kernels/backproject.cl
@matze The bug leads to artifacts in the case of a small number of projections.
> Wrong access to the sinogram has been corrected.

- src/ufo-interpolate-task.c
Before the interval was left-opened, i.e. for 3 images one would get the following `alpha` values:
* 0.33
* 0.66
* 1
which is not what I expect, because the first interpolated result should simply be the "first" input to the filter, the same for last, i.e. the `alpha` values are:
* 0.0
* 0.5
* 1.0
> Interpolate with closed interval on both ends

- docs/filters.rst
- src/CMakeLists.txt
- src/config.h.in
- src/readers/ufo-edf-reader.c
- src/readers/ufo-edf-reader.h
- src/readers/ufo-hdf5-reader.c
- src/readers/ufo-hdf5-reader.h
- src/readers/ufo-reader.c
- src/readers/ufo-reader.h
- src/readers/ufo-tiff-reader.c
- src/readers/ufo-tiff-reader.h
- src/ufo-monitor-task.c
- src/ufo-monitor-task.h
- src/ufo-read-task.c
- src/ufo-write-task.c
- src/ufo-write-task.h
- src/writers/ufo-hdf5-writer.c
- src/writers/ufo-hdf5-writer.h
- src/writers/ufo-raw-writer.c
- src/writers/ufo-raw-writer.h
- src/writers/ufo-tiff-writer.c
- src/writers/ufo-tiff-writer.h
- src/writers/ufo-writer.c
- src/writers/ufo-writer.h
This PR changes the structure of the readers to fix things like #63 and ease addition of more readers, e.g. HDF5. As a nice side effect we can still build a basic EDF or HDF5 reader if libtiff is not available.
> Restructure I/O and add HDF5 support

- docs/filters.rst
- src/CMakeLists.txt
- src/ufo-calculate-task.c
- src/ufo-calculate-task.h
Simplifies calculating arithmetic expressions, especially useful with `ufo-launch`. You access the value in the input via `v` and it's index via `x` (I took the convention from ImageJ).
Examples:
* Initialize data with *1* or make x-gradient:
```bash
$ ufo-launch dummy-data ! calculate expression="1" ! null
$ ufo-launch dummy-data width=256 height=256 ! calculate expression="x % 256" ! null
```
* Take the negative logarithm of a flat-corrected projection:
```bash
$ ufo-launch read="flatcorr*.tif" ! calculate expression="-log(v)" ! null
```
* Compute sinc on 1D input:
```bash
$ ufo-launch dummy-data width=256 height=1 ! calculate expression="sin((float) x) / x" ! null
```
> Add calculate task

- src/ufo-stack-task.c
Modify StackTask to reflect the changes in the commit https://github.com/ufo-kit/ufo-core/commit/ce21698cdb187ed71cb3e23c70923fab9bccc6a2. 
It now stack ``number`` of inputs, pause to generate output and then continue stacking. ``number`` is a property of this filter.
> Update StackTask filter: stack every [number] inputs

- src/ufo-backproject-task.c
instead of the requisition dimensions because by the burst mode we get a
sinogram with less rows than the total number of projections.
Tiny change but it was quite annoying to have to set both the number of projections and angular step in case of burst mode.
> fbp: Use number of projs to compute angle step

- src/kernels/rescale.cl
These bloody factors...
Now the kernel doesn't shift.
> rescale: Add 0.5 to the coordinates in the kernel

- src/readers/ufo-raw-reader.c
- src/ufo-read-task.c
which is important for skipping headers.
For example, Andor Neo outputs raw files with headers. @matze please check if I hooked up all the stuff properly.
> raw-reader: Enable offset to the first image byte

- src/kernels/backproject.cl
I squeezed out 20% performance increase from a GTX Titan. However, I need help from @matze because I can't find things like `DEVICE_GEFORCE_GTX_TITAN_BLACK` anywhere and that needs to be done properly here.
BTW we should start thinking about some micro-optimizations for particular architectures, i.e. work group sizes, number of projections processed at the same time by laminography, loop unrolling like the one here and many more. In the best case the make system will determine the architecture and concrete devices and do the thing. Otherwise we could use a bunch of flags or maybe some customization tool, if it exists for such a project.
> Backproject titan

- src/ufo-memory-in-task.c
- src/ufo-memory-in-task.h
In order to handover data to UFO which are not consisting of 32-Bit floats, the incoming data will be converted depending on the set bit depth.
This is analog to filters like stdin-reader.
> Adds Bitdepth to memory-in generator

- docs/examples.rst
- docs/generators.rst
- docs/sinks.rst
- src/CMakeLists.txt
- src/meson.build
- src/ufo-zmq-common.h
- src/ufo-zmq-pub-task.c
- src/ufo-zmq-pub-task.h
- src/ufo-zmq-sub-task.c
- src/ufo-zmq-sub-task.h
Hello all and especially @tfarago and @tekinbicer, this is the PR that will eventually allow us to integrate UFO pipelines with (almost) arbitrary ZeroMQ producers and consumers. The main addition of this PR are two tasks `zmq-pub`, a sink that publishes data, and `zmq-sub`, a source that subscribes to data. As of now, it is somewhat working with itself however there are numerous issues, that need to be solved before this can be merged and be useful in a broader sense.
Right now, I [adapted](https://github.com/ufo-kit/ufo-filters/blob/5b9150637b98f8bc79b849c7cab111bbebaff0b1/src/ufo-zmq-common.h) Tekin's format to send the geometry for each item however a lot more properties need to be sent as well. Right now, I see two or three layers: the data type of an element (i.e. `dtype` in Numpy), …
> Add ZeroMQ pub/sub support

- tests/meson.build
I'm guessing this slipped because you have the program.
> tests: Use required : false in find_program

- docs/sphinxgobject/domain.py
Since sphinx-doc/sphinx@6c08963f25c0834eab7d31543810c82f4e09daf5, `sphinx.directives` module no longer has `Directive` class imported.
So this class should be imported directly from `docutils.parsers.rst` module.
> sphinx: Fix Directive import to work with Sphinx 1.8

- src/writers/ufo-tiff-writer.c
so that we can open multitiff series by using the bio-format in ImageJ.
A small but essential change, so rather via PR...
> tiff writer: Add photometric tag

- src/CMakeLists.txt
This fixes the CMake file to correctly build the zmq-sub and zmq-pub filter.
> fix CMake for zmq

- src/ufo-transpose-task.c
- src/ufo-transpose-task.h
This fixes a crash when the transpose task was asked for its properties e.g.:
`ufo-query -p transpose`
> Fix properties of transpose task

- docs/filters.rst
- src/CMakeLists.txt
- src/kernels/meson.build
- src/kernels/morphology.cl
- src/meson.build
- src/ufo-find-large-spots-task.c
- src/ufo-find-large-spots-task.h
Finding large spots is useful for removing corrupt image regions, especially for removing broad rings in tomographic reconstruction.
Needs #182.
> Find large spots

- src/ufo-opencl-reduce-task.c
because one processing node needs all the inputs to reduce properly.
> Disable copying of opencl-reduce task

- docs/filters.rst
- src/ufo-stack-task.c
If the number of images in the stack hadn't been a divisor of the number
of input images, the last images would have been dropped. This makes
sure all images are processed and fills the last positions of the stack
(when the total number of stacked images starts to exceed the number of
input images) with arbitrary previous images. Fixes #210.
> stack: force nonfactor generation

- src/ufo-cone-beam-projection-weight-task.c
Because Python3 doesn't like float.
> cone weight: use double instead of float
