ufo-kit/ufo-filters

- src/CMakeLists.txt
- src/kernels/pad.cl
- src/ufo-pad-task.c
- src/ufo-pad-task.h
which supports all OpenCL addressing modes.
> Add pad task

- src/readers/ufo-tiff-reader.c
Should I merge such obvious things without a PR next time?
> Fix tiff reader roi-height

- docs/filters.rst
- src/ufo-rescale-task.c
Sorry...
I hope it is clean that 2 actually increases the size.
> rescale: Fix parameter descriptions

- src/kernels/fft.cl
- src/ufo-fft-task.c
- src/ufo-ifft-task.c
tested against
```
export n=2 
ufo-launch read path='./data/input/input-stack.tif' number=$n ! crop width=1024 height=1024 ! stack number=$n ! fft dimensions=2 ! ifft dimensions=2 ! monitor ! write filename=data/res.tif
```
> Update the code to do 2-D fft/ifft in batch mode

- src/kernels/dfi.cl
- src/ufo-dfi-sinc-task.c
Edited the dfi.cl file due to my project, which inlcluds the mirroring part
(hermitian symmetry). Therefore the dfi-sinc-task.c needed a little
change, since less working groups are needed.
> Change of DFI-kernel and dfi-sinc-task

- src/kernels/dfi.cl
Bug fixes due to @ashkarin comment (29.10.2015).
> Bug fixes of the DFI.cl

- src/ufo-filter-task.c
Fixes #103.
@matze please check all the boilerplate. I hope the name of the filter is self-explanatory to a reasonable level...
> filter: Add ramp computed from real space

- src/readers/ufo-edf-reader.c
It is common to have it 1024 bytes long. However, the original specs allow it to
be a multiple of 512 bytes.
And of course I just came across a data set with 2048 byte long headers.
> edf reader: Allow 512-multiple header size

- src/kernels/phase-retrieval.cl
- src/ufo-retrieve-phase-task.c
Remove all FFTs from the task to provide more flexibility.
Now use as: ufo-launch read ! pad ! fft ! retrieve-phase ! ifft ! crop ! write
> Remove fft from ret-phase

- src/ufo-retrieve-phase-task.c
Remove width and height params.
> Remove width and height params.

- src/common/ufo-addressing.h
- src/ufo-lamino-backproject-task.c
- src/ufo-pad-task.c
Enables specification of what will happen with pixels outside of the projection.
> Lamino addressing mode

- src/kernels/templates/center_template.in
- src/kernels/templates/lamino_template.in
- src/kernels/templates/roll_template.in
- src/kernels/templates/z_template.in
caused by shifting it by 0.5 pixel based on the axis.
> lamino: Prevent volume shifting

- docs/filters.rst
- src/CMakeLists.txt
- src/kernels/interpolator.cl
- src/kernels/meson.build
- src/kernels/pad.cl
- src/kernels/reductor.cl
- src/ufo-stitch-task.c
- src/ufo-stitch-task.h
Those couple of lines in Python I sent @matze some time ago translates to this monstrosity :smile: Anyway, the parallel sum should be quite fast, I see speedup of roughly 30x compared to a CPU, but this could of course be further optimized. For now it's OK though I think.
We could extend the parallel sum to do other things and update e.g. the measure task, but that' for another PR.
> Add stitch task

- src/kernels/meson.build
- src/kernels/transpose.cl
- src/ufo-transpose-task.c
It's cca. 70x faster than the CPU implementation.
> Do transpose on GPU

- docs/filters.rst
- src/CMakeLists.txt
- src/kernels/reductor.cl
- src/meson.build
- src/ufo-measure-task.c
Closely related to #155, this shifts the statistics to GPU. It's very preliminary for now and in the end, only one of these two PRs should survive.
> Measure on gpu

- src/readers/ufo-tiff-reader.c
After [ufo-core#166](https://github.com/ufo-kit/ufo-core/pull/166) is merged.
> Add 12 bit support to tiff reader

- src/ufo-write-task.c
which enables us to create files of certain maximum size and in turn to
split writing of multi-image files to multiple files, not just one.
I used bytes instead of number of images, because it is easier to work with when thinking in terms of file systems. E.g. to avoid 4 GB tif limitation, one can directly set the number of bytes a little less than 4 GB.
> Add bytes_per_file property to writer

- docs/filters.rst
- src/kernels/phase-retrieval.cl
- src/ufo-retrieve-phase-task.c
> Phaseretrieval

- docs/filters.rst
- src/CMakeLists.txt
- src/kernels/interpolator.cl
- src/meson.build
- src/ufo-horizontal-interpolate-task.c
- src/ufo-horizontal-interpolate-task.h
which linearly interpolates rows of an image based on a specified mask.
> Add HorizontalInterpolate task

- src/kernels/phase-retrieval.cl
Make sure we don't divide by zero and simplify kernels.
> Fix phaseretrieval

- src/kernels/complex.cl
> Make c_conj work with opencl task

- docs/filters.rst
- src/CMakeLists.txt
- src/meson.build
- src/ufo-sliding-stack-task.c
- src/ufo-sliding-stack-task.h
> Add sliding-stack task

- docs/filters.rst
- src/kernels/phase-retrieval.cl
- src/ufo-retrieve-phase-task.c
> phase retrieval: enable separate x and y distance

- contrib/CMakeLists.txt
- contrib/meson.build
- src/CMakeLists.txt
- src/meson.build
Do not replace anything, just let the file names be.
> Don't force non-dash task names

- docs/filters.rst
- src/kernels/phase-retrieval.cl
- src/ufo-retrieve-phase-task.c
> retrieve-phase: Add multi-distance CTF support

- docs/generators.rst
- src/readers/ufo-edf-reader.c
- src/readers/ufo-hdf5-reader.c
- src/readers/ufo-raw-reader.c
- src/readers/ufo-reader.c
- src/readers/ufo-reader.h
- src/readers/ufo-tiff-reader.c
- src/ufo-read-task.c
- tests/CMakeLists.txt
- tests/check-multipage-readers
- tests/make-input-multipage-readers
- tests/meson.build
- tests/test-multipage-readers.sh
Now it will be possible to skip images in multipage files.
> Image step

- docs/filters.rst
- src/kernels/filter.cl
which is very useful for DMM stripes.
> filter-stipes: enable horizontal-sigma to be 0

- src/writers/ufo-writer.c
which lets people specify one end and let UFO compute the other.
> writer: determine either end of intensity limits

- docs/filters.rst
- src/kernels/edge.cl
- src/ufo-detect-edge-task.c
This allows us to precisely control where the operators reach when they find themselves on image boundaries.
> Detect edge addressing mode

- CMakeLists.txt
- meson.build
- meson_options.txt
This is getting annoying on the servers.
> meson: make docs optional
